# Generated by Django 4.2.30 on 2026-06-09 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Handle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('team', models.CharField(blank=True, choices=[('404', '404 Brain not found!'), ('da_koders', 'Da_Koders')], default='', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='themes', to='voting.project')),
                ('suggested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggested_themes', to='voting.handle')),
            ],
        ),
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('handle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ideas', to='voting.handle')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ideas', to='voting.project')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='voting.handle')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='voting.theme')),
            ],
            options={
                'unique_together': {('theme', 'handle')},
            },
        ),
    ]
