# Generated by Django 4.2.30 on 2026-06-09 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('handle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='voting.handle')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='voting.theme')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
