# Generated by Django 4.2.30 on 2026-06-09 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='voting.comment')),
                ('handle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_votes', to='voting.handle')),
            ],
            options={
                'unique_together': {('comment', 'handle')},
            },
        ),
    ]
