# Generated by Django 4.2.30 on 2026-06-09 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_project_owner_is_private'),
        ('voting', '0003_commentvote'),
    ]

    operations = [
    ]
